version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@bingosoft.ru
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - "5050:80"